import React, { createContext, useState, useContext, ReactNode } from 'react';
import { Language } from '../types';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

const translations: Record<Language, Record<string, string>> = {
  es: {
    // Navigation
    "nav.university": "EBERHARD KARLS UNIVERSITÄT TÜBINGEN",
    "nav.project": "PROYECTO DFG - ROMANISCHES SEMINAR",
    "nav.title": "Revistas Culturales 2.0",
    "nav.subtitle": "Portal de Investigación",
    "nav.home": "Home",
    "nav.blog": "Blog",
    "nav.library": "Biblioteca virtual",
    "nav.tutorials": "\"How To\": Our Tutorials",
    "nav.network": "Red de participantes",
    "nav.publications": "Publicaciones",
    "nav.bibliography": "Bibliografía",
    "nav.links": "Enlaces",
    "nav.catalog": "Explorador",
    "nav.lab": "Laboratorio",
    
    // Home Content
    "home.about_title": "Revistas culturales 2.0",
    "home.about_subtitle": "Revistas culturales 2.0: ¿de qué se trata?",
    "home.about_text_1": "El portal Revistas culturales 2.0 está diseñado como un entorno virtual de investigación para investigadores de revistas culturales históricas en lengua española y para todos los interesados en este tema. Por revista 2.0 se suele entender una publicación periódica contemporánea que se sirve de las tecnologías interactivas y colaborativas de la llamada Web 2.0. Con el portal Revistas culturales 2.0, sin embargo, queremos que tales tecnologías sirvan para enriquecer la investigación sobre revistas históricas de la modernidad, lo cual nos permitirá complementar los estudios hermenéuticos y pormenorizados que se han venido haciendo de determinadas revistas utilizadas como casos ejemplares.",
    "home.about_text_2": "De esta forma nos proponemos abrir nuevos caminos metodológicos en la era de la digitalización masiva de estos materiales. Una de las tareas que queremos acometer con este portal es la de orientar sobre proyectos actuales de digitalización de revistas culturales hispánicas, tanto de España como de América Latina, y otra, no menos importante, la de impulsar el uso de herramientas y tecnologías de las humanidades digitales para trabajar con estos materiales.",
    "home.read_more": "Leer más",
    "home.posted_on": "Posted on",
    "home.by": "By",
    "home.comment": "para comentar",
    "home.login_to": "Inicie sesión",

    // Sidebar
    "sidebar.search_placeholder": "Buscar...",
    "sidebar.recent_posts": "Entradas de blog recientes",
    "sidebar.more": "Más",
    "sidebar.navigation": "Navegación",
    "sidebar.recent_content": "Contenido reciente",
    "sidebar.advanced_search": "Búsqueda avanzada",
    "sidebar.twitter": "Twitter Timeline",
    "sidebar.login": "Inicio de sesión",
    "sidebar.username": "Nombre de usuario",
    "sidebar.password": "Contraseña",
    "sidebar.request_password": "Solicitar una nueva contraseña",
    "sidebar.login_btn": "Iniciar sesión",

    // Hero
    "hero.tag": "Humanidades Digitales & Archivos Históricos",
    "hero.title_prefix": "Redescubriendo las",
    "hero.title_highlight": "Revistas Culturales",
    "hero.title_suffix": "de América Latina y Europa",
    "hero.description": "Una plataforma abierta para la investigación, visualización y análisis computacional de publicaciones periódicas históricas (1900-1950).",
    "hero.search_placeholder": "Buscar por título, autor o año (ej. 'Amauta 1926')...",
    "hero.explore_btn": "Explorar",
    "hero.stats_docs": "Documentos",
    "hero.stats_countries": "Países",
    "hero.stats_start": "Inicio Archivo",
    "hero.stats_end": "Fin Archivo",

    // Catalog
    "catalog.filters": "Filtros",
    "catalog.search": "Buscar",
    "catalog.keyword": "Palabra clave...",
    "catalog.country": "País de Edición",
    "catalog.period": "Periodo",
    "catalog.results": "Resultados",
    "catalog.general_title": "Catálogo General",
    "catalog.showing": "Mostrando",
    "catalog.found": "documentos encontrados",
    "catalog.no_results": "No se encontraron resultados",
    "catalog.try_adjust": "Intenta ajustar los filtros de búsqueda.",
    "catalog.view_doc": "Ver Documento",

    // Document Viewer
    "doc.back": "Volver",
    "doc.page": "Página",
    "doc.of": "de",
    "doc.tab_metadata": "Ficha Técnica",
    "doc.tab_analysis": "Análisis IA",
    "doc.general_info": "Información General",
    "doc.publisher": "Publicación",
    "doc.place": "Lugar de Edición",
    "doc.date": "Fecha",
    "doc.description": "Descripción",
    "doc.topics": "Temas",
    "doc.ai_title": "Asistente de Investigación",
    "doc.ai_desc": "Utiliza inteligencia artificial para generar un análisis historiográfico y encontrar conexiones latentes en este documento.",
    "doc.ai_btn": "Generar Análisis",
    "doc.ai_analyzing": "Analizando metadatos...",
    "doc.ai_disclaimer": "Generado por Gemini 2.5 Flash. Siempre verifique con fuentes primarias.",

    // Lab
    "lab.title": "Laboratorio de Humanidades Digitales",
    "lab.desc": "El Laboratorio ofrece herramientas de lectura distante para analizar el corpus de Revistas Culturales 2.0. Estas visualizaciones no son meras ilustraciones, sino instrumentos hermenéuticos para formular nuevas hipótesis sobre la modernidad latinoamericana.",
    "lab.tab_network": "Grafo de Redes",
    "lab.tab_timeline": "Línea de Tiempo",
    "lab.network_title": "Redes Intelectuales Transnacionales",
    "lab.network_desc": "El gráfico de redes permite visualizar las conexiones interpersonales y temáticas que sostuvieron el campo cultural de la época.",
    "lab.network_tip": "Tip: Arrastre los nodos para reorganizar la red y descubrir clusters de influencia.",
    "lab.legend": "Leyenda",
    "lab.legend_magazine": "Revista",
    "lab.legend_person": "Persona",
    "lab.legend_topic": "Tema",
    
    // Timeline
    "timeline.title": "Cronología de las Revistas Culturales",
    "timeline.desc_p1": "Esta visualización permite observar la simultaneidad y la sucesión de las publicaciones periódicas en América Latina y Europa.",
    "timeline.desc_p2": "Se pueden identificar claramente momentos de efervescencia editorial, como la explosión de revistas de vanguardia a finales de la década de 1920.",
    "timeline.data_title": "Sobre los datos",
    "timeline.data_li1": "Los datos provienen de la base de datos del proyecto DFG.",
    "timeline.data_li2": "Las barras representan el periodo activo de publicación.",
    "timeline.data_li3": "El color agrupa las revistas por país de edición.",
    "timeline.click_tooltip": "Click para ver archivo",

    // ChatBot
    "chat.header": "HD/BOT Cultural Assistant",
    "chat.placeholder": "Escribe tu consulta...",
    "chat.send": "Enviar",
    "chat.welcome_es": "Hola. Soy tu asistente de investigación especializado en revistas culturales históricas. ¿Te ayudo a buscar documentos, analizar temas o explorar conexiones entre autores?",
    "chat.welcome_en": "Hello. I am your research assistant specializing in historical cultural magazines. Can I help you find documents, analyze topics, or explore connections between authors?",
    "chat.welcome_de": "Hallo. Ich bin Ihr Forschungsassistent, spezialisiert auf historische Kulturzeitschriften. Kann ich Ihnen helfen, Dokumente zu finden, Themen zu analysieren oder Verbindungen zu erforschen?",
    "chat.suggestion_search": "Buscar revista",
    "chat.suggestion_recommend": "Recomendaciones",
    "chat.suggestion_advice": "Análisis Contextual",
    "chat.suggestion_translate": "Traducir contenido",

    // Footer
    "footer.desc": "Portal de investigación financiado por la DFG (Deutsche Forschungsgemeinschaft). Este proyecto busca digitalizar, indexar y analizar semánticamente las revistas culturales más significativas de América Latina y Europa (1880-1950).",
    "footer.contact": "Contacto",
    "footer.rights": "Todos los derechos reservados.",
    "footer.legal": "Aviso Legal",
    "footer.privacy": "Privacidad",
    "footer.links": "Enlaces",
    "footer.info": "Informaciónes",
    "footer.coop": "Cooperaciónes"
  },
  en: {
    "nav.university": "EBERHARD KARLS UNIVERSITY OF TÜBINGEN",
    "nav.project": "DFG PROJECT - ROMANCE SEMINAR",
    "nav.title": "Cultural Magazines 2.0",
    "nav.subtitle": "Research Portal",
    "nav.home": "Home",
    "nav.blog": "Blog",
    "nav.library": "Virtual Library",
    "nav.tutorials": "\"How To\": Unsere Tutorials",
    "nav.network": "Participants Network",
    "nav.publications": "Publications",
    "nav.bibliography": "Bibliography",
    "nav.links": "Links",
    "nav.catalog": "Explorer",
    "nav.lab": "Laboratory",

    "home.about_title": "Cultural Magazines 2.0",
    "home.about_subtitle": "Cultural Magazines 2.0: what is it about?",
    "home.about_text_1": "The Cultural Magazines 2.0 portal is designed as a virtual research environment for researchers of historical cultural magazines in Spanish and for all those interested in this topic. Magazine 2.0 usually refers to a contemporary periodical publication that uses the interactive and collaborative technologies of the so-called Web 2.0.",
    "home.about_text_2": "In this way we propose to open new methodological paths in the era of mass digitization of these materials. One of the tasks we want to undertake with this portal is to provide guidance on current digitization projects of Hispanic cultural magazines, both from Spain and Latin America.",
    "home.read_more": "Read more",
    "home.posted_on": "Posted on",
    "home.by": "By",
    "home.comment": "to comment",
    "home.login_to": "Log in",

    "sidebar.search_placeholder": "Search...",
    "sidebar.recent_posts": "Recent Blog Entries",
    "sidebar.more": "More",
    "sidebar.navigation": "Navigation",
    "sidebar.recent_content": "Recent Content",
    "sidebar.advanced_search": "Advanced Search",
    "sidebar.twitter": "Twitter Timeline",
    "sidebar.login": "Log in",
    "sidebar.username": "Username",
    "sidebar.password": "Password",
    "sidebar.request_password": "Request new password",
    "sidebar.login_btn": "Log in",

    "hero.tag": "Digital Humanities & Historical Archives",
    "hero.title_prefix": "Rediscovering the",
    "hero.title_highlight": "Cultural Magazines",
    "hero.title_suffix": "of Latin America and Europe",
    "hero.description": "An open platform for research, visualization, and computational analysis of historical periodicals (1900-1950).",
    "hero.search_placeholder": "Search by title, author, or year (e.g., 'Amauta 1926')...",
    "hero.explore_btn": "Explore",
    "hero.stats_docs": "Documents",
    "hero.stats_countries": "Countries",
    "hero.stats_start": "Archive Start",
    "hero.stats_end": "Archive End",

    "catalog.filters": "Filters",
    "catalog.search": "Search",
    "catalog.keyword": "Keyword...",
    "catalog.country": "Country of Edition",
    "catalog.period": "Time Period",
    "catalog.results": "Results",
    "catalog.general_title": "General Catalog",
    "catalog.showing": "Showing",
    "catalog.found": "documents found",
    "catalog.no_results": "No results found",
    "catalog.try_adjust": "Try adjusting your search filters.",
    "catalog.view_doc": "View Document",

    "doc.back": "Back",
    "doc.page": "Page",
    "doc.of": "of",
    "doc.tab_metadata": "Technical Data",
    "doc.tab_analysis": "AI Analysis",
    "doc.general_info": "General Information",
    "doc.publisher": "Publisher",
    "doc.place": "Place of Edition",
    "doc.date": "Date",
    "doc.description": "Description",
    "doc.topics": "Topics",
    "doc.ai_title": "Research Assistant",
    "doc.ai_desc": "Uses artificial intelligence to generate historiographical analysis and find latent connections in this document.",
    "doc.ai_btn": "Generate Analysis",
    "doc.ai_analyzing": "Analyzing metadata...",
    "doc.ai_disclaimer": "Generated by Gemini 2.5 Flash. Always verify with primary sources.",

    "lab.title": "Digital Humanities Laboratory",
    "lab.desc": "The Laboratory offers distant reading tools to analyze the corpus of Cultural Magazines 2.0. These visualizations are not mere illustrations, but hermeneutic instruments to formulate new hypotheses about Latin American modernity.",
    "lab.tab_network": "Network Graph",
    "lab.tab_timeline": "Timeline",
    "lab.network_title": "Transnational Intellectual Networks",
    "lab.network_desc": "The network graph allows visualizing the interpersonal and thematic connections that sustained the cultural field of the era.",
    "lab.network_tip": "Tip: Drag nodes to reorganize the network and discover influence clusters.",
    "lab.legend": "Legend",
    "lab.legend_magazine": "Magazine",
    "lab.legend_person": "Person",
    "lab.legend_topic": "Topic",

    "timeline.title": "Chronology of Cultural Magazines",
    "timeline.desc_p1": "This visualization allows observing the simultaneity and succession of periodicals in Latin America and Europe.",
    "timeline.desc_p2": "Clearly identifiable are moments of editorial effervescence, such as the explosion of avant-garde magazines in the late 1920s.",
    "timeline.data_title": "About the data",
    "timeline.data_li1": "Data comes from the DFG project database.",
    "timeline.data_li2": "Bars represent the active publication period.",
    "timeline.data_li3": "Color groups magazines by country of edition.",
    "timeline.click_tooltip": "Click to view archive",

    "chat.header": "HD/BOT Cultural Assistant",
    "chat.placeholder": "Type your query...",
    "chat.send": "Send",
    "chat.welcome_es": "Hola. Soy tu asistente de investigación especializado en revistas culturales históricas. ¿Te ayudo a buscar documentos, analizar temas o explorar conexiones entre autores?",
    "chat.welcome_en": "Hello. I am your research assistant specializing in historical cultural magazines. Can I help you find documents, analyze topics, or explore connections between authors?",
    "chat.welcome_de": "Hallo. Ich bin Ihr Forschungsassistent, spezialisiert auf historische Kulturzeitschriften. Kann ich Ihnen helfen, Dokumente zu finden, Themen zu analysieren oder Verbindungen zu erforschen?",
    "chat.suggestion_search": "Search magazine",
    "chat.suggestion_recommend": "Recommendations",
    "chat.suggestion_advice": "Context Analysis",
    "chat.suggestion_translate": "Translate content",

    "footer.desc": "Research portal funded by the DFG (Deutsche Forschungsgemeinschaft). This project aims to digitize, index, and semantically analyze the most significant cultural magazines of Latin America and Europe (1880-1950).",
    "footer.contact": "Contact",
    "footer.rights": "All rights reserved.",
    "footer.legal": "Legal Notice",
    "footer.privacy": "Privacy",
    "footer.links": "Links",
    "footer.info": "Information",
    "footer.coop": "Cooperation"
  },
  de: {
    "nav.university": "EBERHARD KARLS UNIVERSITÄT TÜBINGEN",
    "nav.project": "DFG-PROJEKT - ROMANISCHES SEMINAR",
    "nav.title": "Kulturzeitschriften 2.0",
    "nav.subtitle": "Forschungsportal",
    "nav.home": "Startseite",
    "nav.blog": "Blog",
    "nav.library": "Virtuelle Bibliothek",
    "nav.tutorials": "\"How To\": Unsere Tutorials",
    "nav.network": "Teilnehmernetzwerk",
    "nav.publications": "Veröffentlichungen",
    "nav.bibliography": "Bibliografie",
    "nav.links": "Links",
    "nav.catalog": "Katalog",
    "nav.lab": "Labor",

    "home.about_title": "Kulturzeitschriften 2.0",
    "home.about_subtitle": "Kulturzeitschriften 2.0: worum geht es?",
    "home.about_text_1": "Das Portal Kulturzeitschriften 2.0 ist als virtuelle Forschungsumgebung für Forscher historischer Kulturzeitschriften in spanischer Sprache und für alle an diesem Thema Interessierten konzipiert. Unter Zeitschrift 2.0 versteht man in der Regel eine zeitgenössische periodische Publikation, die sich der interaktiven und kollaborativen Technologien des sogenannten Web 2.0 bedient.",
    "home.about_text_2": "Auf diese Weise schlagen wir vor, neue methodische Wege im Zeitalter der massenhaften Digitalisierung dieser Materialien zu eröffnen. Eine der Aufgaben, die wir mit diesem Portal übernehmen wollen, ist die Orientierung über aktuelle Digitalisierungsprojekte hispanischer Kulturzeitschriften, sowohl aus Spanien als auch aus Lateinamerika.",
    "home.read_more": "Weiterlesen",
    "home.posted_on": "Veröffentlicht am",
    "home.by": "Von",
    "home.comment": "kommentieren",
    "home.login_to": "Anmelden",

    "sidebar.search_placeholder": "Suchen...",
    "sidebar.recent_posts": "Neueste Blogeinträge",
    "sidebar.more": "Mehr",
    "sidebar.navigation": "Navigation",
    "sidebar.recent_content": "Neuer Inhalt",
    "sidebar.advanced_search": "Erweiterte Suche",
    "sidebar.twitter": "Twitter Timeline",
    "sidebar.login": "Anmeldung",
    "sidebar.username": "Benutzername",
    "sidebar.password": "Passwort",
    "sidebar.request_password": "Neues Passwort anfordern",
    "sidebar.login_btn": "Anmelden",

    "hero.tag": "Digitale Geisteswissenschaften & Historische Archive",
    "hero.title_prefix": "Wiederentdeckung der",
    "hero.title_highlight": "Kulturzeitschriften",
    "hero.title_suffix": "aus Lateinamerika und Europa",
    "hero.description": "Eine offene Plattform für die Forschung, Visualisierung und computergestützte Analyse historischer Periodika (1900-1950).",
    "hero.search_placeholder": "Suche nach Titel, Autor oder Jahr (z.B. 'Amauta 1926')...",
    "hero.explore_btn": "Entdecken",
    "hero.stats_docs": "Dokumente",
    "hero.stats_countries": "Länder",
    "hero.stats_start": "Archiv Beginn",
    "hero.stats_end": "Archiv Ende",

    "catalog.filters": "Filter",
    "catalog.search": "Suche",
    "catalog.keyword": "Stichwort...",
    "catalog.country": "Erscheinungsland",
    "catalog.period": "Zeitraum",
    "catalog.results": "Ergebnisse",
    "catalog.general_title": "Gesamtkatalog",
    "catalog.showing": "Zeige",
    "catalog.found": "Dokumente gefunden",
    "catalog.no_results": "Keine Ergebnisse gefunden",
    "catalog.try_adjust": "Versuchen Sie, Ihre Suchfilter anzupassen.",
    "catalog.view_doc": "Dokument ansehen",

    "doc.back": "Zurück",
    "doc.page": "Seite",
    "doc.of": "von",
    "doc.tab_metadata": "Technische Daten",
    "doc.tab_analysis": "KI-Analyse",
    "doc.general_info": "Allgemeine Informationen",
    "doc.publisher": "Herausgeber",
    "doc.place": "Erscheinungsort",
    "doc.date": "Datum",
    "doc.description": "Beschreibung",
    "doc.topics": "Themen",
    "doc.ai_title": "Forschungsassistent",
    "doc.ai_desc": "Nutzt künstliche Intelligenz, um historiographische Analysen zu erstellen und latente Verbindungen in diesem Dokument zu finden.",
    "doc.ai_btn": "Analyse generieren",
    "doc.ai_analyzing": "Analysiere Metadaten...",
    "doc.ai_disclaimer": "Generiert von Gemini 2.5 Flash. Immer mit Primärquellen abgleichen.",

    "lab.title": "Labor für Digitale Geisteswissenschaften",
    "lab.desc": "Das Labor bietet Tools zum 'Distant Reading' zur Analyse des Korpus von Kulturzeitschriften 2.0. Diese Visualisierungen sind keine bloßen Illustrationen, sondern hermeneutische Instrumente zur Formulierung neuer Hypothesen über die lateinamerikanische Moderne.",
    "lab.tab_network": "Netzwerkgraph",
    "lab.tab_timeline": "Zeitleiste",
    "lab.network_title": "Transnationale Intellektuelle Netzwerke",
    "lab.network_desc": "Der Netzwerkgraph ermöglicht die Visualisierung der zwischenmenschlichen und thematischen Verbindungen, die das kulturelle Feld der Zeit trugen.",
    "lab.network_tip": "Tipp: Ziehen Sie die Knoten, um das Netzwerk neu zu ordnen und Einfluss-Cluster zu entdecken.",
    "lab.legend": "Legende",
    "lab.legend_magazine": "Zeitschrift",
    "lab.legend_person": "Person",
    "lab.legend_topic": "Thema",

    "timeline.title": "Chronologie der Kulturzeitschriften",
    "timeline.desc_p1": "Diese Visualisierung ermöglicht die Beobachtung der Gleichzeitigkeit und der Abfolge von Periodika in Lateinamerika und Europa.",
    "timeline.desc_p2": "Deutlich erkennbar sind Momente redaktioneller Aufbruchstimmung, wie die Explosion der Avantgarde-Zeitschriften in den späten 1920er Jahren.",
    "timeline.data_title": "Über die Daten",
    "timeline.data_li1": "Die Daten stammen aus der Datenbank des DFG-Projekts.",
    "timeline.data_li2": "Die Balken stellen den aktiven Publikationszeitraum dar.",
    "timeline.data_li3": "Die Farbe gruppiert die Zeitschriften nach Erscheinungsland.",
    "timeline.click_tooltip": "Klicken zum Anzeigen",

    "chat.header": "HD/BOT Cultural Assistant",
    "chat.placeholder": "Geben Sie Ihre Frage ein...",
    "chat.send": "Senden",
    "chat.welcome_es": "Hola. Soy tu asistente de investigación especializado en revistas culturales históricas. ¿Te ayudo a buscar documentos, analizar temas o explorar conexiones entre autores?",
    "chat.welcome_en": "Hello. I am your research assistant specializing in historical cultural magazines. Can I help you find documents, analyze topics, or explore connections between authors?",
    "chat.welcome_de": "Hallo. Ich bin Ihr Forschungsassistent, spezialisiert auf historische Kulturzeitschriften. Kann ich Ihnen helfen, Dokumente zu finden, Themen zu analysieren oder Verbindungen zu erforschen?",
    "chat.suggestion_search": "Zeitschrift suchen",
    "chat.suggestion_recommend": "Empfehlungen",
    "chat.suggestion_advice": "Kontextanalyse",
    "chat.suggestion_translate": "Inhalte übersetzen",

    "footer.desc": "Forschungsportal gefördert durch die DFG (Deutsche Forschungsgemeinschaft). Dieses Projekt zielt darauf ab, die bedeutendsten Kulturzeitschriften Lateinamerikas und Europas (1880-1950) zu digitalisieren, zu indexieren und semantisch zu analysieren.",
    "footer.contact": "Kontakt",
    "footer.rights": "Alle Rechte vorbehalten.",
    "footer.legal": "Impressum",
    "footer.privacy": "Datenschutz",
    "footer.links": "Links",
    "footer.info": "Informationen",
    "footer.coop": "Kooperationen"
  }
};

export const LanguageProvider: React.FC<{children: ReactNode}> = ({ children }) => {
  const [language, setLanguage] = useState<Language>('es');

  const t = (key: string): string => {
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};